using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    
    public partial class User
    {
        public int UserID { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "This Field is Required!")]
        public string UserName { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "This Field is Required!")]
        public string Email { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "This Field is Required!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string ErrorMessage { get; set; }

        [StringLength(50)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public List<User> UserProfiles { get; set; }

       
    }
}
